const hard_data = {
  quote: {
    symbol: "AAPL",
    companyName: "Apple Inc",
    primaryExchange: "NASDAQ/NGS (GLOBAL SELECT MARKET)",
    calculationPrice: "close",
    open: 122.61,
    openTime: 1614349801574,
    openSource: "official",
    close: 121.26,
    closeTime: 1614373201223,
    closeSource: "official",
    high: 124.85,
    highTime: 1614373199975,
    highSource: "15 minute delayed price",
    low: 121.23,
    lowTime: 1614373199974,
    lowSource: "15 minute delayed price",
    latestPrice: 121.26,
    latestSource: "Close",
    latestTime: "February 26, 2021",
    latestUpdate: 1614373201223,
    latestVolume: 164560394,
    iexRealtimePrice: null,
    iexRealtimeSize: null,
    iexLastUpdated: null,
    delayedPrice: 121.23,
    delayedPriceTime: 1614373199975,
    oddLotDelayedPrice: 121.24,
    oddLotDelayedPriceTime: 1614373199986,
    extendedPrice: 121.76,
    extendedChange: 0.5,
    extendedChangePercent: 0.00412,
    extendedPriceTime: 1614387599049,
    previousClose: 120.99,
    previousVolume: 148199540,
    change: (0.27).toFixed(2),
    changePercent: (0.00223 * 100).toFixed(2),
    volume: 164560394,
    iexMarketPercent: null,
    iexVolume: null,
    avgTotalVolume: 96527505,
    iexBidPrice: null,
    iexBidSize: null,
    iexAskPrice: null,
    iexAskSize: null,
    iexOpen: 121.09,
    iexOpenTime: 1614373625806,
    iexClose: 121.32,
    iexCloseTime: 1614373199891,
    marketCap: 2035740520960,
    peRatio: 32.95,
    week52High: 144.87,
    week52Low: 52.74,
    ytdChange: -0.08254492980708257,
    lastTradeTime: 1614373219993,
    isUSMarketOpen: false,
  },
  company: {
    symbol: "AAPL",
    companyName: "Apple Inc",
    exchange: "NASDAQ/NGS (GLOBAL SELECT MARKET)",
    industry: "Electronic Computer Manufacturing ",
    website: "https://www.apple.com/",
    description:
      "Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. It is considered one of the Big Five companies in the U.S. information technology industry, along with Amazon, Google, Microsoft, and Facebook. Its hardware products include the iPhone smartphone, the iPad tablet computer, the Mac personal computer, the iPod portable media player, the Apple Watch smartwatch, the Apple TV digital media player, the AirPods wireless earbuds, the AirPods Max headphones, and the HomePod smart speaker line. Apple's software includes iOS, iPadOS, macOS, watchOS, and tvOS operating systems, the iTunes media player, the Safari web browser, the Shazam music identifier, and the iLife and iWork creativity and productivity suites, as well as professional applications like Final Cut Pro X, Logic Pro, and Xcode. Its online services include the iTunes Store, the iOS App Store, Mac App Store, Apple Arcade, Apple Music, Apple TV+, iMessage, and iCloud. Other services include Apple Store, Genius Bar, AppleCare, Apple Pay, Apple Pay Cash, and Apple Card. Apple was founded by Steve Jobs, Steve Wozniak, and Ronald Wayne in April 1976 to develop and sell Wozniak's Apple I personal computer, though Wayne sold his share back within 12 days. It was incorporated as Apple Computer, Inc., in January 1977, and sales of its computers, including the Apple I and Apple II, grew quickly.",
    CEO: "Timothy Cook",
    securityName: "Apple Inc",
    issueType: "cs",
    sector: "Manufacturing",
    primarySicCode: 3571,
    employees: 147000,
    tags: [
      "Electronic Technology",
      "Telecommunications Equipment",
      "Manufacturing",
      "Electronic Computer Manufacturing ",
    ],
    address: "1 Apple Park Way",
    address2: null,
    state: "California",
    city: "Cupertino",
    zip: "95014-0642",
    country: "US",
    phone: "14089961010",
  },
  news: [
    {
      datetime: 1614562581000,
      headline:
        "iPhone 13 could come with 1TB of storage, according to new report",
      source: "TechRadar",
      url:
        "https://cloud.iexapis.com/v1/news/article/a2f70446-a532-4f05-b0e1-f015f87576e7",
      summary:
        "According to a new report, Apple's upcoming iPhone 13 may offer up to 1TB of storage.",
      related: "AAPL",
      image:
        "https://cloud.iexapis.com/v1/news/image/a2f70446-a532-4f05-b0e1-f015f87576e7",
      lang: "en",
      hasPaywall: false,
    },
    {
      datetime: 1614553380000,
      headline: "Apple volta a ceder a leis de França",
      source: "Notícias ao Minuto",
      url:
        "https://cloud.iexapis.com/v1/news/article/c1ba0079-b7be-4771-bab3-500ed830b4c4",
      summary:
        "A empresa será obrigada a exibir as avaliações de reparação dos respetivos produtos.",
      related: "AAPL",
      image:
        "https://cloud.iexapis.com/v1/news/image/c1ba0079-b7be-4771-bab3-500ed830b4c4",
      lang: "pt",
      hasPaywall: false,
    },
    {
      datetime: 1614548032000,
      headline: "Apple Shares Short Film ‘Hometown’, Shot on iPhone [VIDEO]",
      source: "iPhone in Canada",
      url:
        "https://cloud.iexapis.com/v1/news/article/fab6458c-602b-4dcf-858b-c224f6726af6",
      summary: "Here is Apple's latest short film that's been Shot on iPhone.",
      related: "AAPL",
      image:
        "https://cloud.iexapis.com/v1/news/image/fab6458c-602b-4dcf-858b-c224f6726af6",
      lang: "en",
      hasPaywall: false,
    },
  ],
};

export default hard_data;
